### ISSUE TITLE
Support collections of dynamic attributes in RuntimePropertiesFrame

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/bpm#15]
Support collections of dynamic attributes in RuntimePropertiesFrame

---
Original issue: https://youtrack.haulmont.com/issue/PL-9266

**Comment by rapekas** [comment]
Issue moved to [cuba-platform/cuba #798](https://github.com/cuba-platform/cuba/issues/798) via [**ZenHub**](https://www.zenhub.com/)
