### ISSUE TITLE
Support collection "enumeration" dynamic attributes

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/bpm#16]
Support collection "enumeration" dynamic attributes

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-9251"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-9267

**Comment by rapekas** [comment]
Issue moved to [cuba-platform/cuba #797](https://github.com/cuba-platform/cuba/issues/797) via [**ZenHub**](https://www.zenhub.com/)
