### ISSUE TITLE
Use standard Gradle compileOnly configuration instead of provided

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/bpm#36]
Related to cuba-platform/cuba-gradle-plugin#27

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[a48d2c88](https://git.haulmont.com/platform/bpm/commit/a48d2c88607ac4b26ae996c7253e545516ca772f) in **master** - Use standard Gradle compileOnly configuration instead of provided #36
