### ISSUE TITLE
 Remove MVC StaticContentController from CUBA

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/bpm#41]
Relates to cuba-platform/cuba#894

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[d94a817f](https://git.haulmont.com/platform/bpm/commit/d94a817fe56c197a66019eae920ec53cfdda0779) in **master** - Remove MVC StaticContentController from CUBA #41

**Comment by andreysubbotin** [comment]
For QA: check that Model works
