### ISSUE TITLE
Process definition deploy action should check the file type and accept only XML files

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/bpm#42]
#### Description of the enhancement

1. Open process definition screen
2. Click Deploy
3. Select any file, except xml
```
SAXParseException: Content is not allowed in prolog.
```

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[b84cb8ca](https://git.haulmont.com/platform/bpm/commit/b84cb8ca95a2cd40af63caca33006a9b2358d140) in **release_6_10** - Process definition deploy action should check the file type and accept only XML files #42

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[e81645cd](https://git.haulmont.com/platform/bpm/commit/e81645cdd99bf7a9feb32f8f40e04a84649299b5) in **master** - Process definition deploy action should check the file type and accept only XML files #42
