### ISSUE TITLE
Create predefined design-time roles for BPM

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/bpm#58]
### Environment

- Platform version: 7.2-SNAPSHOT
- Related issue: https://github.com/cuba-platform/cuba/issues/2172

### Description of the bug or enhancement

Create two roles:

- First Role should allow user to manage bpm processes. All screens should be available.
- Second Role should allow user to work with processes tasks assigned for this user

Roles will appear in the project after adding BPM add-on to the project.

**Comment by gorbunkov** [comment]
Two roles added:
* **bpm-process-admin** - gives access to all BPM screens and entities
* **bpm-process-actor** - gives access to BPM entities that is required to start the process and complete tasks. **Process tasks** screen is not available, if it is required then it must be added by another role.

QA: you can test roles using the https://github.com/cuba-labs/bpm-samples sample. It was migrated to CUBA 7.2-SNAPSHOT
